# Generated by Django 5.1.5 on 2025-02-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentosFrescos', '0002_alter_cliente_ci_alter_cliente_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='usuario',
            new_name='nombre_usuario',
        ),
    ]
