# Generated by Django 5.1.5 on 2025-02-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentosFrescos', '0003_rename_usuario_cliente_nombre_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
